name: IceXRA
version: 2.0
main: eu.icecraft.xrayalerter.XrayAlerter
website: http://icecraft-mc.eu
description: Effective X-ray logging
authors:
  - illusion9
commands:
#  viewxra:
#    description: view log
#    usage: /<command>
  icexra:
    description: reload config
    usage: /<command>
#  tpxra:
#    description: teleport to last alert
#    usage: /<command>